### ISSUE TITLE
Need to calculate byte length of string instead of characer length

### ISSUE THREAD

**Issue by pdiffley** [alekslario/firestore-size#2]
Currently the calculation get a string's size uses the string's `length` property which counts the number of characters in the string. To count the number of bytes in the string you can use `Buffer.byteLength`.

Example: This code print 4 and 9.
`
> let mystr = "åß∂ƒ"
> console.log(mystr.length)
> console.log(Buffer.byteLength(mystr, 'utf-8'))
`

**Comment by alekslario** [comment]
Fixed in 2.0.5. Thanks for pointing that out.
